### ISSUE TITLE
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

### ISSUE THREAD

**Issue by Kyeongrok** [WooilJeong/PublicDataReader#1]
import PublicDataReader as pdr

serviceKey = "PO0%2FZnoDAPq13aXDpR7e7JfTu6xSTlZNATSkgJ0s5sRoRdNcPzlvQgTIJ4ZiiqRwW5EP1Pu2FzefeObZWvZp7A%3D%3D"
Apt = pdr.AptTransactionReader(serviceKey)

이렇게 콜을 했을 때 

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
위 에러가 납니다.

에러가 나는 시점은 AptTransaction.py에 아래 부분입니다.

path_code = "https://raw.githubusercontent.com/WooilJeong/PublicDataReader/f14e4de3410cc0f798a83ee5934070d651cbd67b/docs/%EB%B2%95%EC%A0%95%EB%8F%99%EC%BD%94%EB%93%9C%20%EC%A0%84%EC%B2%B4%EC%9E%90%EB%A3%8C.txt"
code = pd.read_csv(path_code, encoding='cp949', sep='\t')

이 에러가 제꺼에서만 나는걸까요?

**Comment by WooilJeong** [comment]
답변이 늦어서 죄송합니다.
PublicDataReader 를 전면 개선하여 배포하였습니다.
최신 버전 설치 후 시도해보시길 바랍니다.
감사합니다. :)
