### ISSUE TITLE
서비스키 일일트래픽?

### ISSUE THREAD

**Issue by youngjung** [WooilJeong/PublicDataReader#2]
안녕하세요 정우일님 블로그 글 보고 손을 좀 대보고 있습니다.

#1 과 같은 에러메시지를 보고 있는데요,

https://github.com/WooilJeong/PublicDataReader/blob/d6a031dc165ba610ed531ef90009797256dcfc74/PublicDataReader/PublicDataPortal/AptTrade.py#L28

requests.get() 결과물이 아래와 같이 나옵니다. 
``` xml
b'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><response><header><resultCode>99</resultCode><resultMsg>SERVICE KEY IS NOT REGISTERED ERROR.</resultMsg></header></response>'
```
resultCode 99는 기술문서에도 안써있는데 혹시 짐작가는 것 있으신가요?

![image](https://user-images.githubusercontent.com/45905238/81033703-8d680380-8ecf-11ea-8bee-d2b9a63aa551.png)
`일일트래픽` 이 0인데 다른 api 예시들 보면 1000건 이런식이더라고요, 혹시 이게 문제일까요?

**Comment by WooilJeong** [comment]
제 경우엔 첨부해주신 마지막 이미지에 해당하는 부분에 일일 트래픽이 1000000 입니다. 혹시 일일 트래픽을 모두 소진하셨거나, 서비스 이용 신청 관련 이슈가 있으신 건 아닐까 싶습니다.
