### ISSUE TITLE
행정구역 코드 최신 자료 조회 기능 구현

### ISSUE THREAD

**Issue by WooilJeong** [WooilJeong/PublicDataReader#50]
- 행안부 사이트에 올라오는 최신 데이터를 주기적으로 수집하는 기능 (원격 저장소에 저장)
- 원격 저장소에 저장된 최신 데이터를 불러오는 기능

**Comment by JeungHo** [comment]
2024.8.1.이후 8차레 9개 시군구의 자료가 업데이트 되었으나 
저장소의 자료는 변경이 없었습니다.
행정안전부는 법정동(KiKcd_B)과 동일하게 행정동(KiKcd_H 행정구역)에 대한 데이터를 open api로 제공하여 하여야 합니다.

저장소
https://github.com/WooilJeong/PublicDataReader/blob/main/PublicDataReader/raw/

2025.11.04 현재 게시된 자료의 링크를 게시합니다.
https://www.mois.go.kr/frt/bbs/type001/commonSelectBoardArticle.do?bbsId=BBSMSTR_000000000052&nttId=121446

첨부파일 url
url = "https://www.mois.go.kr/cmm/fms/FileDown.do?atchFileId=FILE_001399377CsGSGj&fileSn=3" # layout
url = 'https://www.mois.go.kr/cmm/fms/FileDown.do?atchFileId=FILE_001399377CsGSGj&fileSn=1' # jscode
url = "https://www.mois.go.kr/cmm/fms/FileDown.do?atchFileId=FILE_001399377CsGSGj&fileSn=2" # jscode 말소코드 포함

행정안전부는 행정동코드(KiKcd_H)에 대한 data를 공개하여야 합니다.
KiKmix(행정기관코드 + 관할 법정동코드)는 참고는 하되 데이터가 왜곡될 수 있습니다.

 - KiKcd_H.20251103 → 행정기관코드(행정동)**
 - KiKcd_B.20251103 → 법정동코드(실제주소)
 - KiKmix.20251103  → 행정기관코드 + 관할 법정동코드

생성일자      시도명      시군구명   
20250101  부산광역시    강서구        1
20250131  전라남도     신안군        1
20250310  전북특별자치도  전주시 덕진구    1
20250701  경기도      안양시 만안구    2
                  서울특별시    동대문구       2
20250714  경기도      용인시 처인구    2
20250901  충청북도     음성군        1
20251020  인천광역시    서구         2
20251027  전북특별자치도  전주시 덕진구    1
