### ISSUE TITLE
get_statistic_search 메소드의 인자 오류

### ISSUE THREAD

**Issue by usiohc** [WooilJeong/PublicDataReader#52]
**국내총생산(GDP)(실질, 계절조정, 전기비), 통계표코드 : 200Y002** 값만 리턴받고자 했는데 잘 안되네요...
**200Y001** 는 문제없이 잘 작동합니다

`df = api.get_statistic_item_list("200Y002", "Q", "2000Q1", "2020Q4", "10111")`

> TypeError: Ecos.get_statistic_item_list() takes from 2 to 3 positional arguments but 6 were given

그리고 키워드 인수를 명시하니 오류가 납니다

`df = api.get_statistic_item_list(통계표코드="200Y002", 주기="Q", 검색시작일자="2000Q1", 검색종료일자="2020Q4")
`

> TypeError: Ecos.get_statistic_item_list() got an unexpected keyword argument '주기'

`help(Ecos.get_statistic_search)`
![image](https://github.com/WooilJeong/PublicDataReader/assets/89768234/39f82e92-da83-4ca2-861e-be41ea35774a)

**Comment by WooilJeong** [comment]
KOSIS API 관련 기능을 전면 수정하여, 최신 버전에서는 get_data() 메서드만 사용합니다. PublicDataReader를 최신 버전으로 업데이트 후 사용하시는 것을 권장드립니다. 자세한 사용방법은 아래 링크를 참고하세요.

[KOSIS 통계정보 사용 가이드](https://github.com/WooilJeong/PublicDataReader/blob/main/assets/docs/kosis/Kosis.md)

**Comment by usiohc** [comment]
감사합니다!
