### ISSUE TITLE
[소상공인시장진흥공단] 업종별 상가업소 조회

### ISSUE THREAD

**Issue by yeonjungin** [WooilJeong/PublicDataReader#57]
안녕하세요
[소상공인시장진흥공단] 업종별 상가업소 조회 API 관련하여 질문드립니다.

현재 데이터 조회 시, numOfRows는 최대 1000으로 되어있습니다. 
pageNo가 1로 하드코딩 되어있어서 1000개까지만 가져오기가 가능합니다.
해당 부분 확인 부탁드립니다 ㅠㅠ

감사합니다.

**Comment by WooilJeong** [comment]
@yeonjungin 
확인해보니, 코드 상에는 numOfRows를 99999로 지정했으나, API 서버에서 최대 1000건 까지만 처리하는 것 같습니다. 우선은 아래와 같이 pageNo의 숫자를 임의로 변경하면서 호출해보시는 방향을 권해드립니다.

```
## 반경내 상가업소 조회
df = api.get_data(
    service_name = "반경상가",
    radius = 1000,
    cx = docs.get("lon"),
    cy = docs.get("lat"),
    pageNo = 1,
)
```
